[build-system]
# NOTE required for glob pattern support
requires = [
    "setuptools >= 57.5.0", 
    "scikit-build>=0.13",
    "cmake>=3.18",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]