[build-system]
requires = [
    "setuptools>=57.5.0", # NOTE required for glob pattern support
    "scikit-build>=0.17",
    "cmake>=3.27",
    "ninja>=1.11.1.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "energyplus-core"
version = "0.1.0a0"
description = "EnergyPlus Kernel with Python Bindings"
requires-python = ">=3.8"
readme = "README.md"
license = {file = "LICENSE.txt"}

[project.optional-dependencies]
test = [
    "pytest"
]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "./tests",
]