name: 'Testing'
description: 'Test packaged artifacts'

inputs:
  python_version:
    description: '[Python] Python version for testing'
    required: false
    default: '3.10'
    
  build_dir:
    description: 'Directory containing packages to test'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4
    with:
      clean: false

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python_version }}

  - name: Install packages (wheels)
    shell: sh
    run: |
      python -m pip install ${{ inputs.build_dir }}/*.whl

  - name: Test packages (wheels)
    shell: sh
    run: |
      python -m pip install --upgrade pytest
      python -m pytest
