name: 'Packaging'
description: 'Build and package repository'

inputs:
  python_version:
    description: 'Required Python version'
    required: false
    # NOTE must be >=3.90 as older versions have trouble running `build`
    default: '3.10'
  build_type:
    description: 'CMake Build type'
    required: false
    default: 'Release'
  build_options: 
    description: 'Arguments passed to `python -m build`'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build and package
      shell: sh
      env:
        SKBUILD_CONFIGURE_OPTIONS: |
          ${{ env.BUILD_CONFIGURE_OPTIONS }}

          -D CMAKE_BUILD_TYPE:STRING=${{ inputs.build_type }}

          -D LINK_WITH_PYTHON:BOOL=${{ env.BUILD_COMPONENT_PYTHON_PLUGIN == 'true' && 'ON' || 'OFF' }} 
          -D Python_REQUIRED_VERSION:STRING=${{ steps.setup-python.outputs.python-version }}
          
          -D DOCUMENTATION_BUILD:STRING=${{ env.BUILD_COMPONENT_DOCUMENTATION == 'true' && 'BuildWithAll' || 'DoNotBuild' }}
          ${{ env.BUILD_COMPONENT_DOCUMENTATION == 'true' && '-D TEX_INTERACTION:STRING="batchmode"' || '' }}
        SKBUILD_BUILD_OPTIONS: |
          ${{ env.BUILD_BUILD_OPTIONS }}
      run: |
        # TODO
        set
        python3 -m pip install --upgrade build
        python3 -m build --config-setting=--quiet ${{ inputs.build_options }}

