name: 'Packaging'
description: 'Build and package repository'

inputs:
  python_version:
    description: '[Python] Required Python version'
    required: false
    # NOTE must be >=3.90 as older versions have trouble running `build`
    default: '3.10'

  build_outdir:
    description: '[Build] Output directory (`python -m build`)'
    required: false
    default: 'dist/'
  build_type:
    description: '[Build] Type (CMake)'
    required: false
    default: 'Release'
  build_options: 
    description: '[Build] Additional options (`python -m build`)'
    required: false
    default: ''

  build_component_opengl:
    description: '[Build] Component: OpenGL'
    required: false
    default: 'false'
  build_component_fortran:
    description: '[Build] Component: Fortran'
    required: false
    default: 'false'
  build_component_python_plugin:
    description: '[Build] Component: Python Plugin Support'
    required: false
    default: 'false'
  build_component_doc:
    description: '[Build] Component: Documentation'
    required: false
    default: 'false'

outputs:
  build_dir:
    description: '[Build] Directory containing built packages'
    value: ${{ inputs.build_outdir }}

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4
    with:
      submodules: 'recursive'
      clean: false

  - name: Set up Python
    id: setup-python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python_version }}

  # Linux
  - name: Install build dependency - OpenGL (Linux)
    if: runner.os == 'Linux' && inputs.build_component_opengl == 'true'
    shell: sh
    env: 
      APT::Install-Recommends: 'false'
    run: |
      # NOTE only tested on ubuntu
      sudo apt-get install libxkbcommon-x11-0 xorg-dev libgl1-mesa-dev
  - name: Install build dependency - Documentation (Linux)
    if: runner.os == 'Linux' && inputs.build_component_doc == 'true'
    shell: sh
    env: 
      APT::Install-Recommends: 'false'
    run: |
      # NOTE only tested on ubuntu
      sudo apt-get install texlive texlive-xetex texlive-science 

  # macOS
  # TODO install deps

  # Windows
  - name: Configure MSVC (Windows)
    uses: ilammy/msvc-dev-cmd@v1
    if: runner.os == 'Windows'
  # TODO install deps

  # TODO rm
  #- name: Setup tmate session
  #  uses: mxschmitt/action-tmate@v3

  - name: Build and package
    shell: sh
    env:
      # NOTE use ninja for speed
      CMAKE_GENERATOR: Ninja
      CMAKE_ARGS: |
        ${{ env.CMAKE_ARGS }}

        -D ENABLE_PCH:BOOL=ON

        -D CMAKE_BUILD_TYPE:STRING=${{ inputs.build_type }}

        -D OPENGL_REQUIRED:BOOL=${{ inputs.build_component_opengl == 'true' && 'ON' || 'OFF' }}

        -D BUILD_FORTRAN:BOOL=${{ inputs.build_component_fortran == 'true' && 'ON' || 'OFF' }}

        -D LINK_WITH_PYTHON:BOOL=${{ inputs.build_component_python_plugin == 'true' && 'ON' || 'OFF' }}
        -D Python_REQUIRED_VERSION:STRING=${{ steps.setup-python.outputs.python-version }}
        
        -D DOCUMENTATION_BUILD:STRING=${{ inputs.build_component_doc == 'true' && 'BuildWithAll' || 'DoNotBuild' }}
        ${{ env.BUILD_COMPONENT_DOCUMENTATION == 'true' && '-D TEX_INTERACTION:STRING="batchmode"' || '' }}
    run: |
      python -m pip install --upgrade build
      python -m build --outdir ${{ inputs.build_outdir }} ${{ inputs.build_options }}
