name: Release (Windows)

#on:
#  push:
#    tags:
#      - '*'
on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: windows-latest
    # to move to windows-2022, just make sure to set the Visual Studio generator build to "17 2022"
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        name: [x64, ]  # removed x86 because it won't build packages now
        include:
        - name: x64
          arch: x64
          allow_failure: false
          vs-generator: x64
          package-arch: x86_64
          enable_hardened_runtime: OFF
        # - name: x86
        #   arch: x86
        #   allow_failure: false
        #   vs-generator: Win32
        #   package-arch: i386
        #   enable_hardened_runtime: OFF
        #- name: x64_hardened
        #  arch: x64
        #  allow_failure: false
        #  vs-generator: x64
        #  package-arch: x86_64-HardenedRuntime
        #  enable_hardened_runtime: ON

    permissions:
      # Needed permission to upload the release asset
      contents: write

    steps:
    # TODO documentation support

    # NOTE checkout to ensure action can be found 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Create packages
      uses: ./.github/actions/packaging
      env:
        BUILD_TYPE: Release

        BUILD_COMPONENT_OPENGL: 'false'
        BUILD_COMPONENT_DOCUMENTATION: 'false'
        BUILD_COMPONENT_PYTHON_PLUGIN: 'false'

        BUILD_CONFIGURE_OPTIONS: |
          -D ENABLE_PCH:BOOL=ON
          -D BUILD_FORTRAN:BOOL=OFF

        BUILD_BUILD_OPTIONS: |
          --parallel 1

        CMAKE_BUILD_PARALLEL_LEVEL: 1

        Python_REQUIRED_VERSION: '3.10'

        #CMAKE_GENERATOR: 'Visual Studio 16 2019'

      with:
        # TODO
        build_options: |
          --wheel

        #  --config-setting=--build-option=--generator='Visual Studio 16 2019'

    - name: TODO Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        token: ${{ secrets.GITHUB_TOKEN }}
        release_name: Release ${{ github.event.after }}

    #- name: TODO Publish to PyPI
    #  uses: pypa/gh-action-pypi-publish@v2
    #  with:
    #    user: __token__
    #    password: ${{ secrets.PYPI_API_TOKEN }}
