name: Release (Linux)

#on:
#  push:
#    tags:
#      - '*'
on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  PYTHON_VERSION: '3.10'

  BUILD_COMPONENT_OPENGL: 'false'
  BUILD_COMPONENT_DOCUMENTATION: 'false'
  BUILD_COMPONENT_PYTHON_PLUGIN: 'false'

jobs:
  main:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        #os: [ubuntu-20.04, ubuntu-22.04]
        include:
        #- os: ubuntu-20.04
        #  allow_failure: false
        - os: ubuntu-22.04
          allow_failure: false

    permissions:
      # Needed permission to upload the release asset
      contents: write

    env:
      APT::Install-Recommends: 'false'

    steps:
    - name: Install OpenGL dependencies
      if: env.BUILD_COMPONENT_OPENGL == 'true'
      run: |
        sudo apt-get install libxkbcommon-x11-0 xorg-dev libgl1-mesa-dev

    - name: Install Documentation dependencies
      if: env.BUILD_COMPONENT_DOCUMENTATION == 'true'
      run: |
        sudo apt-get install texlive texlive-xetex texlive-science 

    # NOTE checkout to ensure actions can be found 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create packages
      id: packaging
      uses: ./.github/actions/packaging
      with:
        python_version: ${{ env.PYTHON_VERSION }}
        build_component_opengl: ${{ env.BUILD_COMPONENT_OPENGL }}
        build_component_python_plugin: ${{ env.BUILD_COMPONENT_PYTHON_PLUGIN }}
        build_component_doc: ${{ env.BUILD_COMPONENT_DOCUMENTATION }}
        build_options: |
          --wheel

    - name: Test packages
      uses: ./.github/actions/testing
      with:
        python_version: ${{ env.PYTHON_VERSION }}
        files_wheels: ${{ steps.packaging.outputs.files_wheels }}

    - name: Publish packages
      uses: ./.github/actions/publishing
      with:
        files_wheels: ${{ steps.packaging.outputs.files_wheels }}
        dest_github_release: 'true'
        dest_pypi_test: 'false'
        dest_pypi: 'false'
