name: Test workflow

#on:
#  push:
#    tags:
#      - '*'
on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  BUILD_TYPE: Release

  BUILD_COMPONENT_OPENGL: ${{ false }}
  BUILD_COMPONENT_DOCUMENTATION: ${{ false }}
  BUILD_COMPONENT_PYTHON_PLUGIN: ${{ false }}

  BUILD_CONFIGURE_OPTIONS: |
    -D ENABLE_PCH:BOOL=OFF
    -D BUILD_FORTRAN:BOOL=OFF

  BUILD_BUILD_OPTIONS: |
    -j 2

  Python_REQUIRED_VERSION: 3.8

  APT::Install-Recommends: "false"

jobs:
  release_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install OpenGL dependencies
      if: env.BUILD_COMPONENT_OPENGL == 'true'
      run: |
        echo sudo apt-get install libxkbcommon-x11-0 xorg-dev libgl1-mesa-dev
